CREATE DATABASE IF NOT EXISTS virtd;
CREATE DATABASE IF NOT EXISTS custom_app_db;
CREATE DATABASE IF NOT EXISTS example;

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'QwErTy1234';
GRANT ALL PRIVILEGES ON virtd.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON custom_app_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON example.* TO 'app'@'%';
FLUSH PRIVILEGES;
